version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      radix:
        patterns:
          - "@radix-ui/*"
      types:
        patterns:
          - "@types/*"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@eslint/*"
      next:
        patterns:
          - "next"
          - "eslint-config-next"
          - "@next/*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
